var advance = 0
var rotating = 0;
var angle = 0;
var container, stats, controls;
var camera, scene, renderer;
var posx = 0;
var posy = 0;
var posz = 0;
var clock = new THREE.Clock();
var loader = new THREE.FBXLoader();
var loader2 = new THREE.FBXLoader();
var objLoader = new THREE.OBJLoader();
var materialLoader = new THREE.MaterialLoader();
var light = new THREE.HemisphereLight(0xffffff, 0x444444);
var mixer;
var mixer2;
var star = new THREE.Object3D();
var stars = new Array();
var player = undefined;
var playerObj = new THREE.Object3D();
var collidableMeshList = [];
var jump;